site_name: Amar Dhillon's blog
site_description: A personal blog by Amarjit Singh Dhillon

## Configuration
theme:
  name: material
  custom_dir: !ENV [THEME_DIR, "material"]
  palette: 
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline 
      name: Switch to dark mode
  - scheme: slate 
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.tabs
    - navigation.tracking 
    # When instant loading is enabled, clicks on all internal links will be intercepted and dispatched via XHR without fully reloading the page
    - navigation.instant 
    
    # When expansion is enabled, the left sidebar will expand all collapsible subsections by default, so the user doesn't have to open subsections manually. 
    - navigation.expand 

    # When anchor following for the table of contents is enabled, the sidebar is automatically scrolled so that the active anchor is always visible
    - toc.follow

extra_css:
  - stylesheets/extra.css

# repo_url: https://github.com/amarjitdhillon/CP_2021
# repo_name: My Github Repo

markdown_extensions:
  - pymdownx.mark
  - pymdownx.critic
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed: # for code tabs
      alternate_style: true   
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra:
  social:
    - icon: fontawesome/brands/instagram 
      link: https://instagram.com/amar_dhillon_studio
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCbxj-orGrUOhihmOBJzE_Fg
    - icon: fontawesome/brands/medium 
      link: https://medium.com/@smartsplash
    - icon: fontawesome/brands/github
      link: https://medium.com/@smartsplash
    - icon: fontawesome/brands/youtube
      link: https://medium.com/@smartsplash
    - icon: fontawesome/brands/twitter 
      link: https://medium.com/@smartsplash


plugins:
    - search
    - macros

## Page tree
nav:
  - Home : index.md        
  - Data Structures and Algorithms: 
    - Combination sum   : cp/combination-sum.md
    - Range addtion- 2   : cp/range-addition-2.md

#  ------- System Design ------
  - System design:
    - Concepts:
      - Consistent Hashing: sys_design/concepts/consistentHashing.md
      - Data Partitioning: sys_design/concepts/dataPartitioning.md
      - GraphQL: sys_design/concepts/graphql.md
      - Micro Services: sys_design/concepts/microservices.md

#  --------- Linux -------------
  - Linux:
    - Commands 101 : technical_stuff/linux/linuxCommands.md
    - Grep content : Linux/grepContent.md
    - Update Paths : Linux/updatePaths.md

#  --------- AWS -------------
  - AWS:
    - Basic Concepts: aws/concepts.md
    - Generic Notes: aws/generic_notes.md

    - Auth:
      - API Gateway: aws/api_gw.md
  
    - Compute:
      - Athnea: aws/athnea.md
      - App Sync: aws/appsync.md
      - EC2: aws/ec2.md
      - EKS: aws/eks.md
      - Lambda: aws/lambda.md
  
    - Infrastructure:    
      - IAM : aws/iam.md

    - Caching:    
      - CloudFront: aws/cloudfront.md
      - Elasti Cache: aws/elasticache.md

    - Database:    
      - Dynamo DB: aws/dynamo.md
      - RDS: aws/rds.md

    - ETL:    
      - Glue: aws/glue.md
      
    - Storage:    
      - Glacier: aws/glacier.md
      - EBS: aws/ebs.md
      - EFS: aws/efs.md
      - S3 : aws/s3.md
      - Snow Ball: aws/snowball.md
      - Storage Gateway: aws/storagegw.md

    - Network:    
      - 101 Networking: aws/subnet.md
      - ACL: aws/acl.md
      - Elastic IP: aws/elasticip.md
      - ENI: aws/eni.md
      - Load Balancers: aws/lb.md
      - NAT GW: aws/natgw.md
      - NAT Instance: aws/natinstance.md
      - Route 53: aws/route53.md
      - Security Group: aws/sg.md
      - VPC: aws/vpc.md


    - Monitoring:    
      - Cloud Watch: aws/cloudwatch.md
      - Cloud Trail: aws/cloudwatch.md

    - Misc Services:    
      - Macie: aws/macie.md
      - Orgs: aws/orgs.md

    - Supporting Services:    
      - Auto Scaling: aws/autoScaling.md
      - SQS: aws/sqs.md

    - "NFRs":    
      - Failover: aws/failover.md
      - Read Replics: aws/readReplica.md

#  --------- Azure -------------
  - Azure:
    - Az Concepts: azure/concepts.md
    - Az Commands: azure/az_commands.md
  
    - Compute:    
      - App Service: azure/appservice.md
      - Service Fabric: azure/serviceFabric.md
  
    - ETL:    
      - Data Factory: azure/adf.md
  
    - Misc:    
      - Devops: azure/devops.md
      - Logic App: azure/logicApp.md

    - Network:    
      - API Gateway: azure/api_gateway.md
      - DNS: azure/dns.md
      - Networking Infrastructure: azure/networkingInfra.md
      - VPN Gateway: azure/vpn_gw.md
      - Virtual Networks: azure/vnet.md

    - Security:
      - Active Directory: azure/aad.md
      - Key Vault: azure/keyVault.md
      - WAF: azure/waf.md

    - Storage:    
      - Az Storage: azure/storage.md
      - Container Registry: azure/acr.md
      - Snowflake: azure/snowflake.md

#  --------- K8s -------------
  - Kubernetes:
    - Commands: k8s/commands.md
    - Docker: k8s/arch/docker.md

    - Architecture:
      - Cluster Architecutre: k8s/arch/arch.md
      - API Server: k8s/arch/apiserver.md
      - CNI: k8s/arch/cni.md
      - Kubelet: k8s/arch/kubelet.md
      - Kube Proxy: k8s/arch/kubeproxy.md
      - Scheduler: k8s/arch/scheduler.md

    - Resources:
      - Service: k8s/svc.md
      - Ingress: k8s/ingress.md
      - ETCD: k8s/arch/etcd.md
      - Controller Manager: k8s/arch/controllermgr.md

    - "Demo's":
      - Demo app in Minikube : k8s/poc_minikube.md
      - Deploy K8S using Python: k8s/deployment_python.md


#  --------- Microservices -------------
  - Microservices:
    - Design Patterns:
      - BFF: microservices/designPatterns/bff.md
      - Service Registry: microservices/designPatterns/serviceRegistry.md
      - CQRS: microservices/designPatterns/cqrs.md


#  --------- Tech stuff -------------
  - Technical Stuff:
    - Attach Android device      : technical_stuff/linux/android_device.md
    - Cpanel settings     : technical_stuff/blogs/cpanel/gitAndCpanel.md
    - Delta Lake          : technical_stuff/databricks/Manipulating Tables with Delta Lake Lab.md
    - Downgrade Maven     : technical_stuff/maven/downgrade_maven/index.md
    - Flink               : technical_stuff/installing_flink/flink.md
    - H2 Db in WSO2       : technical_stuff/wso2/h2/wso2.md
    - Java home           : technical_stuff/linux/java_home/index.md
    - JDMC Statements     : technical_stuff/mysql/JdbcStatements.md
    - JMS Queue in WSO2   : technical_stuff/wso2/jms/index.md
    - Mysql 101           : technical_stuff/mysql/mysql_basics.md
    - Wget                : technical_stuff/wget/wget.md
#  --------- AI -------------
  - AI/ML:
    - STAT 101: AI/intro_to_stat.md

#  --------- About me -------------
  - About me: 
    - About me: about.md

